FROM oven/bun:slim AS dependency

WORKDIR /app
COPY package.json .
COPY bun.lock .
ENV NODE_ENV=production
RUN bun install --frozen-lockfile

FROM oven/bun:slim AS builder
WORKDIR /app
COPY . .
COPY --from=dependency /app/node_modules ./node_modules
ENV NODE_ENV=production
RUN bun --bun run build

FROM oven/bun:distroless AS runner
WORKDIR /app
COPY --from=builder /app/public ./public
COPY --from=builder /app/.next/standalone ./
COPY --from=builder /app/.next/static ./.next/static
ENV NODE_ENV=production
ENTRYPOINT [ "bun", "run", "server.js" ]
# CMD ["bun", "run", "server.js"]
