FROM node:current-alpine AS dependency

WORKDIR /app
COPY package.json .
COPY package-lock.json .
RUN npm install --legacy-peer-deps

FROM node:current-alpine AS builder
WORKDIR /app
COPY . .
COPY --from=dependency /app/node_modules ./node_modules
RUN npm run build

FROM gcr.io/distroless/nodejs22-debian12 AS runner
WORKDIR /app
COPY --from=builder /app/public ./public
COPY --from=builder /app/.next/standalone ./
COPY --from=builder /app/.next/static ./.next/static
ENV NODE_ENV=production
CMD ["node", "server.js"]
