FROM oven/bun:canary-slim AS dependency

WORKDIR /app
COPY package.json .
COPY bun.lock .
ENV NODE_ENV=development
RUN bun install --frozen-lockfile

FROM oven/bun:canary-slim AS builder
WORKDIR /app
COPY . .
COPY --from=dependency /app/node_modules ./node_modules
ENV NODE_ENV=development
RUN bun run build:dev

FROM oven/bun:canary-distroless AS runner
WORKDIR /app
COPY --from=builder /app/public ./public
COPY --from=builder /app/.next/standalone ./
COPY --from=builder /app/.next/static ./.next/static
CMD ["server.js"]
