FROM node:current-alpine AS dependency

WORKDIR /app
COPY package.json .
COPY bun.lock .
RUN npm ci -legacy-peer-deps

FROM node:current-alpine AS builder
WORKDIR /app
COPY . .
COPY --from=dependency /app/node_modules ./node_modules
RUN npm run build

FROM node:current-alpine AS runner
WORKDIR /app
COPY --from=builder /app/public ./public
COPY --from=builder /app/.next/standalone ./
COPY --from=builder /app/.next/static ./.next/static
CMD ["node", "server.js"]
