FROM node:current-alpine AS dependency

WORKDIR /app
COPY package.json .
COPY package-lock.json .
RUN npm install --legacy-peer-deps

FROM node:current-alpine AS builder
WORKDIR /app
COPY . .
COPY --from=dependency /app/node_modules ./node_modules
RUN npm run build

FROM node:22-bookworm AS runner
WORKDIR /app
COPY --from=builder /app/public ./public
COPY --from=builder /app/.next/standalone ./
COPY --from=builder /app/.next/static ./.next/static
ENV NODE_ENV=production
ENV NEXT_SHARP_PATH=node_modules/sharp
EXPOSE 3000
CMD ["server.js"]