FROM node:current-alpine AS dependency

WORKDIR /app
COPY package.json .
COPY package-lock.json .
RUN npm install --legacy-peer-deps

FROM node:current-alpine AS builder
WORKDIR /app
COPY . .
COPY --from=dependency /app/node_modules ./node_modules
RUN npm run build

FROM node:current-alpine AS sharp-installer
WORKDIR /app
COPY --from=builder /app/node_modules ./node_modules
RUN npm rebuild sharp

FROM gcr.io/distroless/nodejs22-debian12 AS runner
WORKDIR /app
COPY --from=builder /app/public ./public
COPY --from=builder /app/.next/standalone ./
COPY --from=builder /app/.next/static ./.next/static
COPY --from=sharp-installer /app/node_modules ./node_modules
ENV NODE_ENV=production
ENV NEXT_SHARP_PATH=node_modules/sharp
CMD ["server.js"]